name: iteacher
description: Online Corse Project.
publish_to: 'none'

version: 3.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  audioplayers: ^6.4.0
  auto_mappr: ^2.4.0
  auto_mappr_annotation: ^2.1.0
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  chat_bubbles: 1.6.0
  cloud_firestore: ^5.6.5
  cupertino_icons: ^1.0.2
  device_info_plus: ^11.3.3
  dio: ^5.8.0+1
  equatable: ^2.0.7
  file_picker: ^9.0.2
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_localization: ^0.3.1
  flutter_screenutil: ^5.9.3
  fluttertoast: ^8.2.12
  font_awesome_flutter: ^10.7.0
  freezed: ^3.0.4
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  go_router: ^14.8.1
  google_sign_in: ^6.1.4
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  http: ^1.1.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.8.1
  just_audio: ^0.9.46
  loading_animation_widget: ^1.2.0+4
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  pretty_dio_logger: ^1.4.0
  provider: ^6.1.2
  record: ^6.0.0
  settings_ui: 2.0.2
  shared_preferences: ^2.5.2
  syncfusion_flutter_core: ^29.1.33
  syncfusion_localizations: ^29.1.33
  url_launcher: ^6.1.12
  webview_flutter: ^4.2.2
  youtube_player_flutter: ^9.1.1
dev_dependencies:
  build_runner: ^2.4.15
  flutter_launcher_icons: "^0.14.3"
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/icons/
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
