name: mrjoo
description: Computer Corse project.
publish_to: 'none'

version: 3.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  auto_mappr: ^2.4.0
  auto_mappr_annotation: ^2.1.0
  cloud_firestore: ^5.6.5
  cupertino_icons: ^1.0.2
  dio: ^5.8.0+1
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  fluttertoast: ^8.2.12
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^3.0.0
  google_sign_in: ^6.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  http: ^1.1.0
  intl: ^0.20.2
  json_annotation: ^4.8.1
  json_serializable: ^6.9.0
  loading_animation_widget: ^1.2.0+4
  url_launcher: ^6.1.12
  webview_flutter: ^4.2.2
dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/payment/
    - assets/images/appicon/
    - assets/images/accounts/
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
