// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCNyulwjCDqRV-3Ll12uc3vNKZnbYNGRw',
    appId: '1:99788243357:web:b4cc12fd754115909e2f74',
    messagingSenderId: '99788243357',
    projectId: 'mr-joo--course',
    authDomain: 'mr-joo--course.firebaseapp.com',
    databaseURL: 'https://mr-joo--course-default-rtdb.firebaseio.com',
    storageBucket: 'mr-joo--course.appspot.com',
    measurementId: 'G-WMCWTZMCSN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIAmCaceeD5i2eooCydP2tBsG4vnBL2_A',
    appId: '1:99788243357:android:7f056326f9478b8a9e2f74',
    messagingSenderId: '99788243357',
    projectId: 'mr-joo--course',
    databaseURL: 'https://mr-joo--course-default-rtdb.firebaseio.com',
    storageBucket: 'mr-joo--course.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzUYrOHwV1GtQ0I0B20pa-K442GPQPMp0',
    appId: '1:99788243357:ios:400fde34038101b79e2f74',
    messagingSenderId: '99788243357',
    projectId: 'mr-joo--course',
    databaseURL: 'https://mr-joo--course-default-rtdb.firebaseio.com',
    storageBucket: 'mr-joo--course.appspot.com',
    androidClientId:
        '99788243357-0vfqd9s3hlrgpvr8084rg95n46dglh8v.apps.googleusercontent.com',
    iosClientId:
        '99788243357-2ii4nos008fc2fek7ogvnnfaoh40l50n.apps.googleusercontent.com',
    iosBundleId: 'com.example.mrjoo',
  );
}
